export const BRAND = 'tuangou/setBrand'
export const CATE = 'tuangou/setCate'
export const ORDER = 'tuangou/setOrder'
export const SEX = 'tuangou/setSex'
export const COMMING = 'tuangou/setComming'
export const KEY = 'tuangou/setKey'